spring:
  data:
    mongodb:
      database: library
      port: 27017
      host: localhost
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.library.mongock.changelog
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  level:
    root: info
  file:
    path: target/app.log
hystrix:
  command:
    books:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
